name: template_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloudinary: ^1.2.0
  cached_network_image: ^3.2.3
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.1
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  go_router: ^10.1.2
  google_sign_in: ^6.1.5
  http: ^1.1.0
  intl: any
  mockito: ^5.4.2
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  url_strategy: ^0.2.0
  video_player: ^2.8.7

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_small.png"
  adaptive_icon_background: "assets/images/Logo_small.png"
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
